export const apiErrorCode = {
  THRESHOLD_EXCEEDED: 'THRESHOLD_EXCEEDED',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  DUPLICATED: 'DUPLICATED',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  EMAIL_DUPLICATED: 'EMAIL_DUPLICATED',
  NOT_FOUND: 'NOT_FOUND',
} as const

export type ApiErrorCode = typeof apiErrorCode
