export const interestCode = {
  CREATE_INTEREST_INVALID_PARAMETER: 'CREATE_INTEREST_INVALID_PARAMETER',
  CREATE_INTEREST_IMAGE_TOO_LARGE: 'CREATE_INTEREST_IMAGE_TOO_LARGE',
  UPDATE_INTEREST_INVALID_PARAMETER: 'UPDATE_INTEREST_INVALID_PARAMETER',
  UPDATE_INTEREST_IMAGE_TOO_LARGE: 'UPDATE_INTEREST_IMAGE_TOO_LARGE',
  CREATE_MAJOR_INTEREST_DUPLICATED: 'CREATE_MAJOR_INTEREST_DUPLICATED',
} as const

export type InterestCode = (typeof interestCode)[keyof typeof interestCode]
