export const profileCode = {
  UPDATE_IMAGE_TOO_LARGE: 'PROFILE_UPDATE_IMAGE_TOO_LARGE',
  UPDATE_HANDLE_INVALID_PARAMETER: 'PROFILE_UPDATE_HANDLE_INVALID_PARAMETER',
  UPDATE_HANDLE_DUPLICATED: 'PROFILE_UPDATE_HANDLE_DUPLICATED',
  UPDATE_MOTTO_INVALID_PARAMETER: 'PROFILE_UPDATE_MOTTO_INVALID_PARAMETER',
} as const

export type ProfileCode = (typeof profileCode)[keyof typeof profileCode]
