export const questCode = {
  CREATE_THRESHOLD_EXCEEDED: 'QUEST_CREATE_THRESHOLD_EXCEEDED',
  CREATE_INVALID_PARAMETER: 'QUEST_CREATE_INVALID_PARAMETER',
  UPDATE_INVALID_PARAMETER: 'QUEST_UPDATE_INVALID_PARAMETER',
  SETTING_INVALID_PARAMETER: 'QUEST_SETTING_INVALID_PARAMETER',
  REPEAT_CREATE_THRESHOLD_EXCEEDED: 'QUEST_REPEAT_CREATE_THRESHOLD_EXCEEDED',
  REPEAT_CREATE_INVALID_PARAMETER: 'QUEST_REPEAT_CREATE_INVALID_PARAMETER',
  REPEAT_UPDATE_INVALID_PARAMETER: 'QUEST_REPEAT_UPDATE_INVALID_PARAMETER',
} as const

export type QuestCode = (typeof questCode)[keyof typeof questCode]
